use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

pub fn generate(input: &Path) -> Result<String, String> {
    let bytes =
        std::fs::read(input).map_err(|error| format!("read {}: {error}", input.display()))?;
    let manifest: serde_json::Value = serde_json::from_slice(&bytes)
        .map_err(|error| format!("parse {}: {error}", input.display()))?;
    let prefix = rust_name(
        manifest
            .pointer("/document/name")
            .and_then(serde_json::Value::as_str)
            .unwrap_or("Opui"),
    );
    let nodes = manifest
        .get("nodes")
        .and_then(serde_json::Value::as_object)
        .ok_or_else(|| "manifest requires a nodes object".to_string())?;
    let mut runtime_ids = BTreeMap::new();
    for runtime_id in nodes
        .values()
        .filter_map(|node| node.get("runtime_id").and_then(serde_json::Value::as_str))
    {
        insert_unique(&mut runtime_ids, rust_name(runtime_id), runtime_id)?;
    }
    let mut entrypoints = BTreeMap::new();
    for name in manifest
        .get("entrypoints")
        .and_then(serde_json::Value::as_object)
        .into_iter()
        .flatten()
        .map(|(name, _)| name.as_str())
    {
        insert_unique(&mut entrypoints, rust_name(name), name)?;
    }

    let mut output = String::new();
    writeln!(
        output,
        "// @generated by `just designer-bindings`; do not edit.\n"
    )
    .unwrap();
    write_enum(&mut output, &format!("{prefix}Node"), &runtime_ids);
    output.push('\n');
    write_enum(&mut output, &format!("{prefix}Entrypoint"), &entrypoints);
    Ok(output)
}

pub fn write_or_check(input: &Path, output: &Path, check: bool) -> Result<(), String> {
    let generated = generate(input)?;
    if check {
        let current = std::fs::read_to_string(output)
            .map_err(|error| format!("read {}: {error}", output.display()))?;
        if current != generated {
            return Err(format!(
                "{} is stale; run `just designer-bindings`",
                output.display()
            ));
        }
        return Ok(());
    }
    std::fs::write(output, generated)
        .map_err(|error| format!("write {}: {error}", output.display()))
}

fn insert_unique<'a>(
    values: &mut BTreeMap<String, &'a str>,
    variant: String,
    value: &'a str,
) -> Result<(), String> {
    if let Some(previous) = values.insert(variant.clone(), value) {
        return Err(format!(
            "`{previous}` and `{value}` both map to Rust variant `{variant}`"
        ));
    }
    Ok(())
}

fn write_enum(output: &mut String, name: &str, values: &BTreeMap<String, &str>) {
    writeln!(
        output,
        "#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]\npub enum {name} {{"
    )
    .unwrap();
    for variant in values.keys() {
        writeln!(output, "    {variant},").unwrap();
    }
    writeln!(output, "}}\n\nimpl {name} {{").unwrap();
    writeln!(output, "    #[rustfmt::skip]").unwrap();
    writeln!(output, "    pub const ALL: [Self; {}] = [", values.len()).unwrap();
    for variant in values.keys() {
        writeln!(output, "        Self::{variant},").unwrap();
    }
    writeln!(
        output,
        "    ];\n\n    pub const fn as_str(self) -> &'static str {{\n        match self {{"
    )
    .unwrap();
    for (variant, value) in values {
        writeln!(output, "            Self::{variant} => {value:?},").unwrap();
    }
    writeln!(output, "        }}\n    }}\n\n    pub fn from_value(value: &str) -> Option<Self> {{\n        match value {{").unwrap();
    for (variant, value) in values {
        writeln!(output, "            {value:?} => Some(Self::{variant}),").unwrap();
    }
    writeln!(output, "            _ => None,\n        }}\n    }}\n}}").unwrap();
}

fn rust_name(value: &str) -> String {
    let mut output = String::new();
    let mut capitalize = true;
    for character in value.chars() {
        if character.is_ascii_alphanumeric() {
            if capitalize {
                output.push(character.to_ascii_uppercase());
                capitalize = false;
            } else {
                output.push(character.to_ascii_lowercase());
            }
        } else {
            capitalize = true;
        }
    }
    if output.is_empty() {
        output.push_str("Value");
    } else if output.as_bytes()[0].is_ascii_digit() {
        output.insert(0, 'N');
    }
    if matches!(output.as_str(), "Self" | "Super" | "Crate") {
        output.insert_str(0, "Value");
    }
    output
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_bindings_are_sorted_and_typed() {
        let output = generate(Path::new("generated/showcase.opui")).unwrap();
        assert!(output.contains("pub enum ShowcaseNode"));
        assert!(output.contains("MainMenuPlay"));
        assert!(output.contains("pub enum ShowcaseEntrypoint"));
        assert_eq!(
            output,
            generate(Path::new("generated/showcase.opui")).unwrap()
        );
    }
}
